server:
  port: 8081
spring:
  application:
    name: cloudgateway
  cloud:
    gateway:
      routes:
      - id: consumer-service
        uri: lb://consumer
        predicates:
        - Path=/api-consumer/**
